version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 1000
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.

exclude_patterns:
- "tests/"
- "**/static/admin/"
- "**/testutils.py"
- "migrations/"
- "node_modules/"
- "**/lib/"
- ".github/"
- ".gitlab/"
- "docs/"
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/solr/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "**/polyfill.js"

plugins:
  bandit:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  pylint:
    enabled: true
    plugins:
      - django
      - celery
    django_settings_module: atlas.settings.prod
    checks:
      wrong-import-order:
        enabled: false
  radon:
    enabled: true
  scss-lint:
    enabled: false # conflicts with stylelint
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
  stylelint:
    enabled: true
