stages:
  - static
  - test
  - deploy
  - docs

include:
  - template: Code-Quality.gitlab-ci.yml
  - local: '/.gitlab/py.yml'
  - local: '/.gitlab/static.yml'
  - local: '/.gitlab/lint.yml'
  - local: '/.gitlab/docs.yml'
  - local: '/.gitlab/publish.yml'

code_quality:
  services:
  tags:
    - cq-sans-dind
  artifacts:
    paths: [gl-code-quality-report.json]

metrics:
  script:
    - echo 'metric_name metric_value' > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt
