ci:
  autofix_commit_msg: 'chore(pre-commit): autofix run'
  autoupdate_commit_msg: 'chore(pre-commit): autoupdate hooks'
  autoupdate_branch: dev

default_install_hook_types:
  - pre-commit
  - commit-msg

exclude: >
  (?x)(
      migrations/|
      docs/|
      node_modules/|
      static/lib/|
      CACHE/|
      vendor/
  )

files: ^atlas/

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.17.2
    hooks:
      - id: djlint-django
