language: python
os:  linux
dist: focal

jobs:
  include:
    - python: 3.6
      env: TOXV=py36
      os: osx
    - python: 3.7
      env: TOXV=py37
      os: osx
    - python: 3.8
      env: TOXV=py38
      os: osx
    - python: 3.9
      env: TOXV=py39
      os: osx
    - python: 3.6
      env: TOXV=py36
      os: linux
    - python: 3.7
      env: TOXV=py37
      os: linux
    - python: 3.8
      env: TOXV=py38
      os: linux
    - python: 3.9
      env: TOXV=py39
      os: linux
services:
  - redis
addons:
    postgresql: "13"
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libxmlsec1; fi
  - pip install tox-travis poetry codecov
  - python --version
before_script:
  - sudo psql -c 'create database atlas;' -U postgres
script:
  - tox -e clean,$TOXV,cov
after_success:
  - codecov
