language: python
os: linux
dist: focal

jobs:
  include:
    - name: linux python 3.6
      python: 3.6
    - name: linux python 3.7
      python: 3.7
    - name: linux python 3.8
      python: 3.8
    - name: linux python 3.9
      python: 3.9
    - name: osx python 3.6
      os: osx
      language: shell
      before_install: brew install python@3.6
    - name: osx python 3.7
      os: osx
      language: shell
      before_install: brew install python@3.7
    - name: osx python 3.8
      os: osx
      language: shell
      before_install: brew install python@3.8
    - name: osx python 3.9
      os: osx
      language: shell
      before_install: brew install python@3.9
    - name: windows python 3.6
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
    - name: windows python 3.7
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.0
    - name: windows python 3.8
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
    - name: windows python 3.9
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.9.0

services:
  - redis

addons:
    postgresql: "13"

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libxmlsec1; fi
  - pip install tox-travis poetry codecov
  - python --version

before_script:
  - sudo psql -c 'create database atlas;' -U postgres

script:
  - tox -e clean,test,cov

after_success:
  - codecov
