language: python
os: linux
dist: focal

jobs:
  include:
    - name: linux python 3.6
      python: 3.6
    - name: linux python 3.7
      python: 3.7
    - name: linux python 3.8
      python: 3.8
    - name: linux python 3.9
      python: 3.9
    - name: osx
      os: osx
      language: shell
      osx_image: xcode11.6
      before_install:
        - brew install libxmlsec1
        - pyenv install 3.6.13
        - pyenv install 3.7.10
        - pyenv install 3.8.9
        - pyenv install 3.9.4
        - pyenv global 3.6.13 3.7.10 3.8.9 3.9.4
      before_script:
        - brew services stop postgres
        - sudo rm -f /usr/local/var/postgres/postmaster.pid
        - brew services start postgres
        - sudo psql -c 'create database atlas;' -U postgres
      script:
        - tox -e clean,py36,py37,py38,py39,cov
    - name: windows
      os: windows
      language: shell
      env: PGPASSWORD=12345
      before_install:
        - choco install postgresql13 --params '/Password:12345'
        - choco install python --version 3.6.8
        - C:/Python36/python.exe -m ensurepip
      install:
        - C:/Python36/python.exe -m pip install tox-travis poetry codecov
      before_script:
        - C:/"Program Files"/PostgreSQL/13/bin/psql.exe -c 'create database atlas;' -U postgres

services:
  - redis

addons:
    postgresql: "13"

before_install:
  - sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl

install:
  - python -m pip install tox-travis poetry codecov
  - python --version

before_script:
  - sudo psql -c 'create database atlas;' -U postgres

script:
  - tox -e clean,test,cov

after_success:
  - codecov
