branches:
  except:
  - gh-pages
language: python
os: linux
dist: focal
jobs:
  include:
  - name: linux python 3.6
    python: 3.6
  - name: linux python 3.7
    python: 3.7
  - name: linux python 3.8
    python: 3.8
  - name: linux python 3.9
    python: 3.9
  - name: osx
    os: osx
    language: shell
    osx_image: xcode11.6
    before_install:
    - brew install libxmlsec1 redis
    - pyenv install 3.6.13
    - pyenv install 3.7.10
    - pyenv install 3.8.9
    - pyenv install 3.9.4
    - pyenv global 3.6.13 3.7.10 3.8.9 3.9.4
    before_script:
    - sudo rm -rf /usr/local/var/postgres
    - initdb /usr/local/var/postgres -E utf8 -U postgres
    - brew services start postgresql
    - sudo psql -c 'create database atlas;' -U postgres
    - brew services start redis
    script:
    - tox -e clean,py36,py37,py38,py39,cov
  - name: windows
    os: windows
    language: shell
    env: PGPASSWORD=12345
    before_install:
    - choco install postgresql13 --params '/Password:12345'
    - choco install python --version 3.9.5
    - choco install redis-64
    - C:/Python39/python.exe -m ensurepip
    install:
    - C:/Python39/python.exe -m pip install tox-travis poetry codecov
    before_script:
    - C:/"Program Files"/PostgreSQL/13/bin/psql.exe -c 'create database atlas;' -U
      postgres
    - C:/"Program Files"/PostgreSQL/13/bin/psql.exe -c '\l' -U postgres
    script:
    - C:/Python39/python.exe -m tox -e clean,test,cov
    after_success: echo "ok"
  - name: browser stack
    python: 3.8
    env:
    - BROWSERSTACK_BUILD_NAME="$TRAVIS_COMMIT"
    - BROWSERSTACK_PROJECT_NAME="Atlas Py"
    addons:
      postgresql: '13'
      browserstack:
        username: "$BROWSERSTACK_USERNAME"
    script:
    - tox -e clean,browsertest,cov
services:
- redis
addons:
  postgresql: '13'
before_install:
- sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
install:
- python -m pip install tox-travis poetry codecov
- python --version
script:
- tox -e clean,test,cov
after_success:
- codecov
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: CRoFEWUzQxkdqlDZK72wd4e/llKuc6YYJ+KLd+UHfYzZZvj1HQgLM0kx34PkdGpn0mWh6XOAc7xsFRMZYTURfvJz2pDE81WZVe6cjUzPVL6rXL/hIUDQFBFZ89Px8zmGsK2WWFmW0Y9+AozbQTtUFUxOJK8Myh5bJ4Ui855HfzDkP5CGu974u+KEx18YAk8Ck7Ds/vbcUe1LUSO4oI1eY8NfuqYUV4EERAMEa2V4F0uIdz3dvAmzNP5t30z6HajSJ+VDucTXZ4irII6rPZY1I7bpByQbPqLVUYiHfe1y7MAvGfplMb8areIAd7FfmMTAdkdiG5S9D2AoAGkD8bADflcliB/JPtYRHryCY+g2DbfbbB+h2WPheoV6cVZaKbeam2aFCck0b6NMSUgtLlAc9W+K40Dz8PDkvovAMbhbC/DveFXRgMrbf9IMovrezjjrmuNYs+x85vQ7mHvLXj5vFXNfb5/yaTOsztu2DrT45TBTnik3ChssqDXQhE238P9JxrNEvAbaCBIx7xXspX5stbI6ayrvTwU2DIgWDLLhTuII2l5Vsv7Q+g+Utk4oigk8cBsi8LQQlUFCA/40R1YTz+KUnj1R0KjNn/p/Wm2cc/qfkFSSbzd4Hk5KReGtpBqNXFPEd4Rb26QS5zmAoYyvduFGAerJNF2YUj97Qa6M2KQ=
