branches:
  except:
  - gh-pages
language: python
os: linux
dist: focal
jobs:
  include:
  - name: linux python 3.6
    python: 3.6
  - name: linux python 3.7
    python: 3.7
  - name: linux python 3.8
    python: 3.8
  - name: linux python 3.9
    python: 3.9
  - name: osx
    os: osx
    language: shell
    osx_image: xcode11.6
    before_install:
    - brew install libxmlsec1 redis
    - pyenv install 3.6.13
    - pyenv install 3.7.10
    - pyenv install 3.8.9
    - pyenv install 3.9.4
    - pyenv global 3.6.13 3.7.10 3.8.9 3.9.4
    before_script:
    - sudo rm -rf /usr/local/var/postgres
    - initdb /usr/local/var/postgres -E utf8 -U postgres
    - brew services start postgresql
    - sudo psql -c 'create database atlas;' -U postgres
    - brew services start redis
    script:
    - tox -e clean,py36,py37,py38,py39,cov
  - name: windows
    os: windows
    language: shell
    env: PGPASSWORD=12345
    before_install:
    - choco install postgresql13 --params '/Password:12345'
    - choco install python --version 3.9.5
    - choco install redis-64
    - C:/Python39/python.exe -m ensurepip
    install:
    - C:/Python39/python.exe -m pip install tox-travis poetry codecov
    before_script:
    - C:/"Program Files"/PostgreSQL/13/bin/psql.exe -c 'create database atlas;' -U
      postgres
    - C:/"Program Files"/PostgreSQL/13/bin/psql.exe -c '\l' -U postgres
    script:
    - C:/Python39/python.exe -m tox -e clean,test,cov
    after_success: echo "ok"
  - name: browser stack
    python: 3.8
    env:
    - BROWSERSTACK_BUILD_NAME="$TRAVIS_COMMIT"
    - BROWSERSTACK_PROJECT_NAME="Atlas Py"
    addons:
      postgresql: '13'
      browserstack:
        username: "$BROWSERSTACK_USERNAME"
        access_key:
          secure: MpgfHoyUTGA2DQi370TeDBaCnTBJAANURQwHtol0sLxNzaEIMZ7W8/wfdF6pw8xcO0pKeh72QKY7IAhCIG8+nTtpuTyfitL4ccjU4xls12p8lSUslW11fARqOsWITC0NwKdNJNC2vFHzHWZbNgeGWlL0vQ96r6am6eq/vXrPNysnsFarzXSgsreLA7QCanGFN7eAFF0QuTx7zEDvwFCidEk3tMq+RybX8wEqykCDre2q5WSLwuUTxxSKG/rOCUBk+hDmgC7C2qPzG5V+XMdpg3kdH9DNYnw2MlLGRDK44hHzoxmSUIDaKq0CCFZ/WWfwpFHJN4/A4q1SVMw8IU4StMEtL08yEnaudUPxkBwaAYooZ6j7dO8tOx8KXVITqP3wjFS/f90zSBBBoSSFvFLsCnUyJ71pVNWONqBSSJtD8uOE0NKMOiXJGjEwvgtoX+pn6ZGfV+FIBLXY3oLTwT+ufuqLg/nZkIkYtre1rbVa0YCKTduRX6KLgkAS9+s1VLFE8jdi9jG5wT1ZbNDPq5QvLZMXuqVK/pKGbShnvhZ1ayH2JpxIjtubcKNMehEBqWi5JyzFnBn0qy72tB+NRa0Bv0Yra6l9dD0N2lZNPs/B4Fz5lnocjuhA7Z3I0DoP1YcaesvXgaudOJBnX/N0uUoM2MrPonGRuL6edE8GEABUz5w=
    script:
    - tox -e clean,browsertest,cov
services:
- redis
addons:
  postgresql: '13'
before_install:
- sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
install:
- python -m pip install tox-travis poetry codecov
- python --version
script:
- tox -e clean,test,cov
after_success:
- codecov
notifications:
  email:
    on_success: change
    on_failure: always
