language: python
os: linux
dist: focal

jobs:
  include:
    - name: linux python 3.6
      python: 3.6
    - name: linux python 3.7
      python: 3.7
    - name: linux python 3.8
      python: 3.8
    - name: linux python 3.9
      python: 3.9
    - name: osx xcode12
      os: osx
      language: shell
      osx_image: xcode12

services:
  - redis

addons:
    postgresql: "13"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libxmlsec1; fi
  - pip install tox-travis poetry codecov
  - python --version

before_script:
  - sudo psql -c 'create database atlas;' -U postgres

script:
  - tox -e clean,test,cov

after_success:
  - codecov
