language: python
os: linux
dist: focal
jobs:
  include:
    - python: 3.6
      env: TOXV=py36
    - python: 3.7
      env: TOXV=py37
    - python: 3.8
      env: TOXV=py38
    - python: 3.9
      env: TOXV=py39
services:
  - redis
addons:
    postgresql: "13"
before_install:
  - sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
  - pip install tox-travis poetry codecov
  - python --version
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sudo psql -c 'create database atlas;' -U postgres
script:
  - tox -e clean,$TOXV,cov
after_success:
  - codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT