language: python
os: linux
dist: focal

jobs:
  include:
    - name: linux python 3.6
      python: 3.6
    - name: linux python 3.7
      python: 3.7
    - name: linux python 3.8
      python: 3.8
    - name: linux python 3.9
      python: 3.9
    - name: osx
      os: osx
      language: shell
      osx_image: xcode12.5
      before_install:
        - brew install libxml2 libxmlsec1 pkg-config postgres
        - pyenv install 3.6.13 3.7.10 3.8.9 3.9.4
      before_script:
        - brew services start postgres
        - sudo psql -c 'create database atlas;' -U postgres
      script:
        - tox -e clean,py36,py37,py38,py39,cov
    - name: windows
      os: windows
      language: shell
      env: POSTGRES_PASS=12345
      before_install:
        - choco install postgresql --params '/Password:12345'
        - choco install python --version 3.6.13
        - choco install python --version 3.7.10
        - choco install python --version 3.8.9
        - choco install python --version 3.9.5
      before_script:
        - psql -c 'create database atlas;' -U postgres
      script:
        - tox -e clean,py36,py37,py38,py39,cov

services:
  - redis

addons:
    postgresql: "13"

before_install:
  - sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl

install:
  - pip install tox-travis poetry codecov
  - python --version

before_script:
  - sudo psql -c 'create database atlas;' -U postgres

script:
  - tox -e clean,test,cov

after_success:
  - codecov
