language: python
os:
 - linux
 - osx
dist: focal

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

services:
  - redis
addons:
    postgresql: "13"
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libxmlsec1; fi
  - pip install tox-travis poetry codecov
  - python --version
before_script:
  - sudo psql -c 'create database atlas;' -U postgres
script:
  - tox -e clean,py,cov
after_success:
  - codecov
