name: "Demo Deploy"

on:
  schedule:
    - cron: '1 * * * *'

  workflow_dispatch:

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: nyakaz73/heroku-django-deploy@v0.68
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email_address: ${{ secrets.HEROKU_EMAIL }}
          use_git: true
          working-directory: ./atlas