name: Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 12345
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Poetry
        uses: snok/install-poetry@v1
      - name: install deps
        run: |
          cd solr && docker run -d -v "$PWD:/var/solr/mine" -p 8983:8983 --name solr_dev solr:8; docker exec solr_dev bash -c "source /var/solr/mine/setup_cores.sh;"
          python -m pip install tox poetry codecov
          sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
          poetry install
      - name: setup db
        run: |
          poetry run python manage.py migrate
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          PGPASSWORD: 12345
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          FLASK_ENV: test
          FLASK_DEBUG: false
          FLASK_APP: web
          FLASK_RUN_PORT: 4998
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.9.x
          lhci autorun
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          PGPASSWORD: 12345
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
