name: quality

on: [push, pull_request,workflow_dispatch]

jobs:
  lint:
    name: Quality

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node Deps
        run: |
         npm --version
         npm install

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: snok/install-poetry@v1

      - name: Install Python Deps
        run: poetry install

      - name: Test
        run: poetry run tox -e lint
