name: "pre-release"

on:
  push:
    tags:
      - "*.*.*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest

    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "npm Build"
        run: |
         npm install
         tar -czvf ${{ env.TAG }}_build.tar.gz atlas solr publish

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: "${{ env.TAG }}_build.tar.gz"
